export const outerWrapper: string;
export const lowProfile: string;
export const label: string;
export const labelHidden: string;
export const inputWrapper: string;
export const disabled: string;
export const focused: string;
export const input: string;
export const inputDark: string;
