export const setToken: string;
export const terminal: string;
export const title: string;
export const error: string;
export const explanations: string;
export const explanationHeader: string;
export const explanationParagraph: string;
export const input: string;
export const actions: string;
